/**
 * Export a scan report to markdown. Findings already carry only redacted
 * evidence, so the exported file is safe to share with a team.
 */
import * as fs from 'fs/promises';
import * as path from 'path';
import type { Finding, ScanReport, Severity } from '../types';

export class ExportManager {
  /** Write `deployready-report.md` to `outDir`; returns the path written. */
  static async saveMarkdown(report: ScanReport, outDir: string): Promise<string> {
    const file = path.join(outDir, 'deployready-report.md');
    await fs.writeFile(file, ExportManager.toMarkdown(report), 'utf8');
    return file;
  }

  static toMarkdown(report: ScanReport): string {
    const lines: string[] = [];
    lines.push(`# DeployReady Report`);
    lines.push('');
    lines.push(`- **Target:** \`${report.target}\``);
    lines.push(`- **Score:** ${report.score}/100`);
    lines.push(`- **Stack:** ${report.stack.stack} (${report.stack.language})`);
    lines.push(`- **Scanned:** ${report.startedAt}`);
    lines.push(
      `- **Findings:** ${report.summary.critical} critical · ${report.summary.warning} warning · ${report.summary.info} info`,
    );
    lines.push('');

    if (report.aiSummary) {
      lines.push(`## AI Summary`);
      lines.push('');
      lines.push(report.aiSummary);
      lines.push('');
    }

    for (const sev of ['critical', 'warning', 'info'] as Severity[]) {
      const group = report.findings.filter((f) => f.severity === sev);
      if (!group.length) continue;
      lines.push(`## ${sev.toUpperCase()} (${group.length})`);
      lines.push('');
      for (const f of group) lines.push(...ExportManager.findingMd(f));
      lines.push('');
    }

    lines.push('---');
    lines.push(`_Generated by DeployReady v${report.version}_`);
    return lines.join('\n');
  }

  private static findingMd(f: Finding): string[] {
    const loc = f.endpoint ?? (f.file ? `${f.file}${f.line ? `:${f.line}` : ''}` : '—');
    const out = [`### ${f.title}`, '', `- **Where:** \`${loc}\``, `- **Source:** ${f.source}`];
    if (f.owasp) out.push(`- **OWASP:** ${f.owasp}`);
    if (f.cwe) out.push(`- **CWE:** ${f.cwe}`);
    if (f.evidence) out.push(`- **Evidence:** \`${f.evidence}\``);
    out.push(`- **Description:** ${f.description}`);
    out.push(`- **Fix:** ${f.recommendation}`);
    out.push('');
    return out;
  }
}
