/**
 * Renders a scan report as a self-contained HTML/CSS dashboard, branded to
 * match deployready.dev (permanent dark theme, accent #00ff88).
 *
 * - Zero external resources (no CDN, no fonts, no network requests) — safe to
 *   open offline and never phones home. The only outbound URL is an <a> link to
 *   the DeployReady site, which loads nothing on its own.
 * - Every dynamic value is HTML-escaped. Findings come from user code, so the
 *   report itself must not become an XSS vector when opened in a browser.
 */
import type { Finding, ScanReport, Severity } from '../types';
import { PlatformRecommender, type PlatformPick } from '../deploy/PlatformRecommender';

const SITE = 'https://www.deployready.dev/';
const ACCENT = '#00ff88';

const COLORS: Record<Severity, string> = {
  critical: '#ef4444',
  warning: '#f59e0b',
  info: '#3b82f6',
};

export class HtmlReporter {
  static render(report: ScanReport): string {
    const scoreColor = report.score >= 80 ? ACCENT : report.score >= 50 ? '#f59e0b' : '#ef4444';
    const { critical, warning, info } = report.summary;
    const deploy = renderDeploy(report);

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>DeployReady Report — ${esc(report.target)}</title>
<style>${CSS}</style>
</head>
<body>
<header class="topbar">
  <a class="brand" href="${SITE}" target="_blank" rel="noopener noreferrer">⚡ <span>Deploy</span>Ready</a>
  <div class="meta">${esc(report.stack.stack)} · ${esc(report.stack.language)} · ${report.graph.fileCount} files · ${report.graph.routes.length} routes</div>
</header>

<main>
  <section class="hero">
    <div class="gauge" style="--p:${report.score};--c:${scoreColor}">
      <div class="gauge-inner"><div class="score">${report.score}</div><div class="score-label">/ 100</div></div>
    </div>
    <div class="hero-side">
      <h1>Production Readiness</h1>
      <p class="target">${esc(report.target)}</p>
      <p class="when">Scanned ${esc(report.startedAt)} · v${esc(report.version)}</p>
      <div class="cards">
        ${card('Critical', critical, COLORS.critical)}
        ${card('Warning', warning, COLORS.warning)}
        ${card('Info', info, COLORS.info)}
      </div>
    </div>
  </section>

  ${report.aiSummary ? `<section class="ai"><h2>🤖 AI Summary</h2><p>${esc(report.aiSummary)}</p></section>` : ''}

  ${deploy}

  <section class="filters">
    <button class="f active" data-f="all">All (${report.summary.total})</button>
    <button class="f" data-f="critical">Critical (${critical})</button>
    <button class="f" data-f="warning">Warning (${warning})</button>
    <button class="f" data-f="info">Info (${info})</button>
  </section>

  <section class="findings">
    ${report.findings.map(findingCard).join('\n') || '<p class="empty">✓ No issues found.</p>'}
  </section>
</main>

<footer>Generated by <a href="${SITE}" target="_blank" rel="noopener noreferrer">DeployReady</a> · local-first production-readiness scanner</footer>

<script>
(function(){
  var btns=document.querySelectorAll('.f');
  btns.forEach(function(b){b.addEventListener('click',function(){
    btns.forEach(function(x){x.classList.remove('active')});b.classList.add('active');
    var f=b.getAttribute('data-f');
    document.querySelectorAll('.finding').forEach(function(el){
      el.style.display=(f==='all'||el.getAttribute('data-sev')===f)?'':'none';
    });
  })});
})();
</script>
</body>
</html>`;
  }
}

function renderDeploy(report: ScanReport): string {
  let rec;
  try {
    rec = PlatformRecommender.recommend({ stack: report.stack, graph: report.graph });
  } catch {
    return '';
  }
  const pick = (p: PlatformPick): string =>
    `<a class="plat" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.name)}${p.free ? '<span class="free">free</span>' : ''}</a>`;
  const alts = rec.alternatives.map(pick).join(' ');
  const split = rec.split.recommended
    ? `<p class="split">✂ <strong>Split recommended:</strong> ${esc(rec.split.reason)}${
        rec.split.frontend ? ` <br/>frontend → ${pick(rec.split.frontend)}` : ''
      }${rec.split.backend ? ` · backend → ${pick(rec.split.backend)}` : ''}</p>`
    : '';
  const notes = rec.notes.length
    ? `<ul class="notes">${rec.notes.map((n) => `<li>${esc(n)}</li>`).join('')}</ul>`
    : '';
  return `<section class="deploy">
  <h2>🚀 Recommended deployment <span class="kind">${esc(rec.size)} ${esc(rec.kind)} app</span></h2>
  <p class="primary">${pick(rec.primary)} <span class="why">${esc(rec.primary.reason)}</span></p>
  ${alts ? `<p class="alts"><span class="lbl">Alternatives:</span> ${alts}</p>` : ''}
  ${split}
  ${notes}
</section>`;
}

function card(label: string, n: number, color: string): string {
  return `<div class="stat"><div class="stat-n" style="color:${color}">${n}</div><div class="stat-l">${label}</div></div>`;
}

function findingCard(f: Finding): string {
  const loc = f.endpoint ?? (f.file ? `${f.file}${f.line ? `:${f.line}` : ''}` : '');
  const refs = [f.owasp, f.cwe].filter(Boolean).map((r) => `<span class="ref">${esc(r!)}</span>`).join('');
  return `<article class="finding" data-sev="${f.severity}" style="--c:${COLORS[f.severity]}">
  <div class="f-head">
    <span class="badge" style="background:${COLORS[f.severity]}">${f.severity.toUpperCase()}</span>
    <span class="f-title">${esc(f.title)}</span>
    <span class="src">${esc(f.source)}</span>
  </div>
  <div class="f-meta">${loc ? `<code>${esc(loc)}</code>` : ''} ${refs}</div>
  <p class="f-desc">${esc(f.description)}</p>
  ${f.evidence ? `<pre class="f-ev">${esc(f.evidence)}</pre>` : ''}
  <p class="f-fix"><strong>Fix:</strong> ${esc(f.recommendation)}</p>
</article>`;
}

/** Escape the five HTML-significant characters. */
function esc(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const CSS = `
:root{color-scheme:dark}
*{box-sizing:border-box}
body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:#0a0a0a;color:#f0f0f0;line-height:1.5;background-image:radial-gradient(circle,rgba(255,255,255,0.04) 1px,transparent 1px);background-size:32px 32px}
a{color:${ACCENT};text-decoration:none}
.topbar{display:flex;justify-content:space-between;align-items:center;padding:16px 28px;background:#111111;border-bottom:1px solid rgba(255,255,255,0.08)}
.brand{font-weight:700;font-size:20px;color:#f0f0f0;font-family:ui-monospace,"JetBrains Mono",monospace}.brand span{color:${ACCENT}}
.meta{color:#888;font-size:13px;font-family:ui-monospace,monospace}
main{max-width:980px;margin:0 auto;padding:28px}
.hero{display:flex;gap:32px;align-items:center;flex-wrap:wrap;margin-bottom:28px}
.gauge{width:160px;height:160px;border-radius:50%;background:conic-gradient(var(--c) calc(var(--p)*1%),#1a1a1a 0);display:flex;align-items:center;justify-content:center;flex:0 0 auto;box-shadow:0 0 40px rgba(0,255,136,0.12)}
.gauge-inner{width:124px;height:124px;border-radius:50%;background:#0a0a0a;display:flex;flex-direction:column;align-items:center;justify-content:center}
.score{font-size:44px;font-weight:800;line-height:1;font-family:ui-monospace,monospace}.score-label{color:#888;font-size:13px}
.hero-side h1{margin:0 0 4px;font-size:24px;font-family:ui-monospace,"JetBrains Mono",monospace}
.target{margin:0;color:#cbd5e1;font-family:ui-monospace,monospace;font-size:13px;word-break:break-all}
.when{margin:2px 0 14px;color:#666;font-size:12px}
.cards{display:flex;gap:12px}
.stat{background:#111111;border:1px solid rgba(255,255,255,0.08);border-radius:10px;padding:10px 18px;text-align:center;min-width:84px}
.stat-n{font-size:26px;font-weight:800;font-family:ui-monospace,monospace}.stat-l{color:#888;font-size:12px;text-transform:uppercase;letter-spacing:.04em}
.ai{background:#0c1f15;border:1px solid rgba(0,255,136,0.25);border-radius:12px;padding:16px 20px;margin-bottom:24px}
.ai h2{margin:0 0 6px;font-size:16px;color:${ACCENT}}.ai p{margin:0;color:#cbd5e1}
.deploy{background:#111111;border:1px solid rgba(255,255,255,0.08);border-left:3px solid ${ACCENT};border-radius:12px;padding:16px 20px;margin-bottom:24px}
.deploy h2{margin:0 0 10px;font-size:16px;color:#f0f0f0}
.deploy .kind{color:#888;font-size:12px;text-transform:uppercase;letter-spacing:.04em;margin-left:8px;font-weight:400}
.deploy .primary{margin:0 0 8px;font-size:15px}.deploy .why{color:#888;font-size:13px}
.deploy .alts{margin:8px 0;color:#888;font-size:13px}.deploy .lbl{margin-right:6px}
.plat{display:inline-flex;align-items:center;gap:6px;background:#1a1a1a;border:1px solid rgba(255,255,255,0.1);border-radius:999px;padding:3px 12px;margin:2px 4px 2px 0;font-size:13px;color:#f0f0f0}
.plat .free{background:${ACCENT};color:#0a0a0a;font-weight:700;font-size:10px;border-radius:6px;padding:1px 6px;text-transform:uppercase}
.deploy .split{margin:10px 0 4px;color:#f59e0b;font-size:13px}
.deploy .notes{margin:8px 0 0;padding-left:18px;color:#888;font-size:12px}
.filters{display:flex;gap:8px;margin-bottom:16px;flex-wrap:wrap}
.f{background:#111111;color:#cbd5e1;border:1px solid rgba(255,255,255,0.1);border-radius:999px;padding:6px 14px;font-size:13px;cursor:pointer}
.f.active{background:${ACCENT};color:#0a0a0a;border-color:${ACCENT};font-weight:600}
.finding{background:#111111;border:1px solid rgba(255,255,255,0.08);border-left:4px solid var(--c);border-radius:10px;padding:14px 18px;margin-bottom:12px}
.f-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap}
.badge{color:#0a0a0a;font-weight:700;font-size:11px;padding:2px 8px;border-radius:6px}
.f-title{font-weight:600}.src{margin-left:auto;color:#666;font-size:12px;text-transform:uppercase}
.f-meta{margin:6px 0;display:flex;gap:8px;align-items:center;flex-wrap:wrap}
.f-meta code{background:#0a0a0a;border:1px solid rgba(255,255,255,0.08);border-radius:6px;padding:2px 8px;font-size:12px;color:${ACCENT}}
.ref{background:#1a1a1a;color:#888;border-radius:6px;padding:2px 8px;font-size:11px}
.f-desc{margin:6px 0;color:#cbd5e1}
.f-ev{background:#0a0a0a;border:1px solid rgba(255,255,255,0.08);border-radius:8px;padding:8px 12px;overflow:auto;font-size:12px;color:#fca5a5;margin:8px 0}
.f-fix{margin:6px 0 0;color:#a7f3d0;font-size:14px}
.empty{color:${ACCENT};font-size:18px;text-align:center;padding:40px}
footer{text-align:center;color:#555;font-size:12px;padding:24px}
`;
